package generatedconfig

// Code generated by flyb. DO NOT EDIT.

const FieldsTagsValidationKey = "fieldsTagsValidation"
const FieldsTextInputValueKey = "fieldsTextInputValue"
const FieldsTextInputValueValidationKey = "fieldsTextInputValueValidation"

var TextByKey = map[string]string{
	FieldsTextInputValueKey: "example value",
}

type CommandFlag struct {
	Kind    string
	Name    string
	Schema  []string
	Schemas [][]string
}

type CommandSpec struct {
	CommandPath []string
	AdminOnly   bool
	Flags       []CommandFlag
}

var ValidationByKey = map[string]CommandSpec{
	FieldsTagsValidationKey: {
		CommandPath: []string{"validate", "tags"},
		AdminOnly:   false,
		Flags: []CommandFlag{
			{
				Kind:    "string",
				Name:    "tags",
				Schema:  []string{"schema", "string", "--alphabetic"},
				Schemas: [][]string{[]string{"schema", "repeatable", "--min-length", "1", "--max-length", "20"}},
			},
		},
	},
	FieldsTextInputValueValidationKey: {
		CommandPath: []string{"validate", "text-input", "value"},
		AdminOnly:   false,
		Flags: []CommandFlag{
			{
				Kind:   "string",
				Name:   "value",
				Schema: []string{"schema", "string", "--required", "--min-length", "1", "--max-length", "120"},
			},
		},
	},
}

var MetaArgsByKey = map[string][]string{
	FieldsTagsValidationKey:           {"meta", "--status", "experimental", "--app", "v2"},
	FieldsTextInputValueKey:           {"meta", "--status", "draft", "--app", "v1"},
	FieldsTextInputValueValidationKey: {"meta", "--status", "draft", "--app", "v1"},
}
