library generated_config;

// Generated by splash. Do not edit.

const String fieldsTagsValidationKey = "fieldsTagsValidation";
const String fieldsTextInputValueKey = "fieldsTextInputValue";
const String fieldsTextInputValueValidationKey = "fieldsTextInputValueValidation";

const Map<String, String> textByKey = {
  fieldsTextInputValueKey: "example value",
};

class CommandFlag {
  final String kind;
  final String name;
  final List<String> schema;
  final List<List<String>> schemas;

  const CommandFlag({
    required this.kind,
    required this.name,
    required this.schema,
    this.schemas = const [],
  });
}

class CommandSpec {
  final List<String> commandPath;
  final bool adminOnly;
  final List<CommandFlag> flags;

  const CommandSpec({
    required this.commandPath,
    required this.adminOnly,
    required this.flags,
  });
}

const Map<String, CommandSpec> validationByKey = {
  fieldsTagsValidationKey: CommandSpec(
    commandPath: ["validate", "tags"],
    adminOnly: false,
    flags: [
      CommandFlag(
        kind: "string",
        name: "tags",
        schema: ["schema", "string", "--alphabetic"],
        schemas: [["schema", "repeatable", "--min-length", "1", "--max-length", "20"]],
      ),
    ],
  ),
  fieldsTextInputValueValidationKey: CommandSpec(
    commandPath: ["validate", "text-input", "value"],
    adminOnly: false,
    flags: [
      CommandFlag(
        kind: "string",
        name: "value",
        schema: ["schema", "string", "--required", "--min-length", "1", "--max-length", "120"],
      ),
    ],
  ),
};

const Map<String, List<String>> metaArgsByKey = {
  fieldsTagsValidationKey: ["meta", "--status", "experimental", "--app", "v2"],
  fieldsTextInputValueKey: ["meta", "--status", "draft", "--app", "v1"],
  fieldsTextInputValueValidationKey: ["meta", "--status", "draft", "--app", "v1"],
};
