package engine

import (
	"bytes"
	"fmt"
	goformat "go/format"
	"sort"
	"strings"
	"unicode"
)

func buildGoSource(cap capResolved, cfg genConfig) ([]byte, error) {
	pkg := cap.GoPackageName
	if strings.TrimSpace(pkg) == "" {
		pkg = "generatedconfig"
	}
	data := buildCodegenData(cap, cfg)
	ids := map[string]string{}
	for _, key := range data.keys {
		id := toPascal(key) + "Key"
		if prev, ok := ids[id]; ok && prev != key {
			return nil, fmt.Errorf("identifier collision between %q and %q (%s)", prev, key, id)
		}
		ids[id] = key
	}
	var b bytes.Buffer
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("// Code generated by splash. DO NOT EDIT.\n\n")
	for _, key := range data.keys {
		id := toPascal(key) + "Key"
		b.WriteString(fmt.Sprintf("const %s = %q\n", id, key))
	}
	b.WriteString("\n")
	if len(data.textByKey) > 0 {
		b.WriteString("var TextByKey = map[string]string{\n")
		for _, key := range sortedMapKeysString(data.textByKey) {
			id := toPascal(key) + "Key"
			b.WriteString(fmt.Sprintf("\t%s: %q,\n", id, data.textByKey[key]))
		}
		b.WriteString("}\n\n")
	}
	if len(data.validatorByKey) > 0 {
		b.WriteString("type CommandFlag struct {\n")
		b.WriteString("\tKind    string\n")
		b.WriteString("\tName    string\n")
		b.WriteString("\tSchema  []string\n")
		b.WriteString("\tSchemas [][]string\n")
		b.WriteString("}\n\n")
		b.WriteString("type CommandSpec struct {\n")
		b.WriteString("\tCommandPath []string\n")
		b.WriteString("\tAdminOnly   bool\n")
		b.WriteString("\tFlags       []CommandFlag\n")
		b.WriteString("}\n\n")
		b.WriteString("var ValidationByKey = map[string]CommandSpec{\n")
		for _, key := range sortedMapKeysSpec(data.validatorByKey) {
			id := toPascal(key) + "Key"
			spec := data.validatorByKey[key]
			b.WriteString(fmt.Sprintf("\t%s: {\n", id))
			b.WriteString(fmt.Sprintf("\t\tCommandPath: %s,\n", goStringSlice(spec.CommandPath)))
			if spec.AdminOnly {
				b.WriteString("\t\tAdminOnly:   true,\n")
			} else {
				b.WriteString("\t\tAdminOnly:   false,\n")
			}
			b.WriteString("\t\tFlags: []CommandFlag{\n")
			for _, fl := range spec.Flags {
				b.WriteString("\t\t\t{\n")
				b.WriteString(fmt.Sprintf("\t\t\t\tKind:   %q,\n", fl.Kind))
				b.WriteString(fmt.Sprintf("\t\t\t\tName:   %q,\n", fl.Name))
				b.WriteString(fmt.Sprintf("\t\t\t\tSchema: %s,\n", goStringSlice(fl.Schema)))
				if len(fl.Schemas) > 0 {
					b.WriteString(fmt.Sprintf("\t\t\t\tSchemas: %s,\n", go2DStringSlice(fl.Schemas)))
				}
				b.WriteString("\t\t\t},\n")
			}
			b.WriteString("\t\t},\n")
			b.WriteString("\t},\n")
		}
		b.WriteString("}\n\n")
	}
	if len(data.metaByKey) > 0 {
		b.WriteString("var MetaArgsByKey = map[string][]string{\n")
		for _, key := range sortedMapKeysSlice(data.metaByKey) {
			id := toPascal(key) + "Key"
			b.WriteString(fmt.Sprintf("\t%s: {", id))
			for i, tok := range data.metaByKey[key] {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(fmt.Sprintf("%q", tok))
			}
			b.WriteString("},\n")
		}
		b.WriteString("}\n")
	}
	formatted, err := goformat.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated go source is not gofmt-compatible: %w", err)
	}
	return formatted, nil
}

func buildDartSource(cap capResolved, cfg genConfig) ([]byte, error) {
	lib := cap.DartLibraryName
	if strings.TrimSpace(lib) == "" {
		lib = "generated_config"
	}
	data := buildCodegenData(cap, cfg)
	ids := map[string]string{}
	for _, key := range data.keys {
		id := toLowerCamel(key) + "Key"
		if prev, ok := ids[id]; ok && prev != key {
			return nil, fmt.Errorf("identifier collision between %q and %q (%s)", prev, key, id)
		}
		ids[id] = key
	}
	var b bytes.Buffer
	b.WriteString("library " + lib + ";\n\n")
	b.WriteString("// Generated by splash. Do not edit.\n\n")
	for _, key := range data.keys {
		id := toLowerCamel(key) + "Key"
		b.WriteString(fmt.Sprintf("const String %s = %q;\n", id, key))
	}
	b.WriteString("\n")
	if len(data.textByKey) > 0 {
		b.WriteString("const Map<String, String> textByKey = {\n")
		for _, key := range sortedMapKeysString(data.textByKey) {
			id := toLowerCamel(key) + "Key"
			b.WriteString(fmt.Sprintf("  %s: %q,\n", id, data.textByKey[key]))
		}
		b.WriteString("};\n\n")
	}
	if len(data.validatorByKey) > 0 {
		b.WriteString("class CommandFlag {\n")
		b.WriteString("  final String kind;\n")
		b.WriteString("  final String name;\n")
		b.WriteString("  final List<String> schema;\n")
		b.WriteString("  final List<List<String>> schemas;\n\n")
		b.WriteString("  const CommandFlag({\n")
		b.WriteString("    required this.kind,\n")
		b.WriteString("    required this.name,\n")
		b.WriteString("    required this.schema,\n")
		b.WriteString("    this.schemas = const [],\n")
		b.WriteString("  });\n")
		b.WriteString("}\n\n")
		b.WriteString("class CommandSpec {\n")
		b.WriteString("  final List<String> commandPath;\n")
		b.WriteString("  final bool adminOnly;\n")
		b.WriteString("  final List<CommandFlag> flags;\n\n")
		b.WriteString("  const CommandSpec({\n")
		b.WriteString("    required this.commandPath,\n")
		b.WriteString("    required this.adminOnly,\n")
		b.WriteString("    required this.flags,\n")
		b.WriteString("  });\n")
		b.WriteString("}\n\n")
		b.WriteString("const Map<String, CommandSpec> validationByKey = {\n")
		for _, key := range sortedMapKeysSpec(data.validatorByKey) {
			id := toLowerCamel(key) + "Key"
			spec := data.validatorByKey[key]
			b.WriteString(fmt.Sprintf("  %s: CommandSpec(\n", id))
			b.WriteString(fmt.Sprintf("    commandPath: %s,\n", dartStringSlice(spec.CommandPath)))
			if spec.AdminOnly {
				b.WriteString("    adminOnly: true,\n")
			} else {
				b.WriteString("    adminOnly: false,\n")
			}
			b.WriteString("    flags: [\n")
			for _, fl := range spec.Flags {
				b.WriteString("      CommandFlag(\n")
				b.WriteString(fmt.Sprintf("        kind: %q,\n", fl.Kind))
				b.WriteString(fmt.Sprintf("        name: %q,\n", fl.Name))
				b.WriteString(fmt.Sprintf("        schema: %s,\n", dartStringSlice(fl.Schema)))
				if len(fl.Schemas) > 0 {
					b.WriteString(fmt.Sprintf("        schemas: %s,\n", dart2DStringSlice(fl.Schemas)))
				}
				b.WriteString("      ),\n")
			}
			b.WriteString("    ],\n")
			b.WriteString("  ),\n")
		}
		b.WriteString("};\n\n")
	}
	if len(data.metaByKey) > 0 {
		b.WriteString("const Map<String, List<String>> metaArgsByKey = {\n")
		for _, key := range sortedMapKeysSlice(data.metaByKey) {
			id := toLowerCamel(key) + "Key"
			b.WriteString(fmt.Sprintf("  %s: [", id))
			for i, tok := range data.metaByKey[key] {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(fmt.Sprintf("%q", tok))
			}
			b.WriteString("],\n")
		}
		b.WriteString("};\n")
	}
	return b.Bytes(), nil
}

func toPascal(s string) string {
	var b strings.Builder
	upperNext := true
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if upperNext {
			b.WriteRune(unicode.ToUpper(r))
			upperNext = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toLowerCamel(s string) string {
	p := toPascal(s)
	if p == "" {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

func sortedMapKeysString(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedMapKeysSpec(m map[string]commandSpecLit) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedMapKeysSlice(m map[string][]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func goStringSlice(items []string) string {
	if len(items) == 0 {
		return "[]string{}"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", s))
	}
	b.WriteString("}")
	return b.String()
}

func go2DStringSlice(items [][]string) string {
	if len(items) == 0 {
		return "[][]string{}"
	}
	var b strings.Builder
	b.WriteString("[][]string{")
	for i, row := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goStringSlice(row))
	}
	b.WriteString("}")
	return b.String()
}

func dartStringSlice(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b strings.Builder
	b.WriteString("[")
	for i, s := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", s))
	}
	b.WriteString("]")
	return b.String()
}

func dart2DStringSlice(items [][]string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b strings.Builder
	b.WriteString("[")
	for i, row := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(dartStringSlice(row))
	}
	b.WriteString("]")
	return b.String()
}

func extractCommandSpec(args map[string]any) (commandSpecLit, bool) {
	if len(args) == 0 {
		return commandSpecLit{}, false
	}
	sections := make([]string, 0, len(args))
	for k := range args {
		sections = append(sections, k)
	}
	sort.Strings(sections)
	first := sections[0]
	raw, ok := args[first].(map[string]any)
	if !ok {
		return commandSpecLit{}, false
	}
	spec := commandSpecLit{}
	if cp, ok := raw["commandPath"].([]any); ok {
		for _, it := range cp {
			if s, ok := it.(string); ok {
				spec.CommandPath = append(spec.CommandPath, s)
			}
		}
	}
	if adminOnly, ok := raw["adminOnly"].(bool); ok {
		spec.AdminOnly = adminOnly
	}
	if flags, ok := raw["flags"].([]any); ok {
		for _, rf := range flags {
			m, ok := rf.(map[string]any)
			if !ok {
				continue
			}
			fl := commandFlagLit{}
			if s, ok := m["kind"].(string); ok {
				fl.Kind = s
			}
			if s, ok := m["name"].(string); ok {
				fl.Name = s
			}
			if sc, ok := m["schema"].([]any); ok {
				for _, it := range sc {
					if s, ok := it.(string); ok {
						fl.Schema = append(fl.Schema, s)
					}
				}
			}
			if scs, ok := m["schemas"].([]any); ok {
				for _, r := range scs {
					rowAny, ok := r.([]any)
					if !ok {
						continue
					}
					row := make([]string, 0, len(rowAny))
					for _, it := range rowAny {
						if s, ok := it.(string); ok {
							row = append(row, s)
						}
					}
					fl.Schemas = append(fl.Schemas, row)
				}
			}
			spec.Flags = append(spec.Flags, fl)
		}
	}
	return spec, true
}

func buildCodegenData(cap capResolved, cfg genConfig) codegenData {
	out := codegenData{
		keys:           make([]string, 0),
		textByKey:      map[string]string{},
		metaByKey:      map[string][]string{},
		validatorByKey: map[string]commandSpecLit{},
	}
	allowed := map[string]struct{}{}
	for _, k := range cap.SupportsNode {
		allowed[k] = struct{}{}
	}
	if _, ok := allowed["text"]; ok {
		for _, e := range cfg.TextEntries {
			out.keys = append(out.keys, e.Key)
			out.textByKey[e.Key] = e.Value
			out.metaByKey[e.Key] = append([]string(nil), e.MetaArgs...)
		}
	}
	if _, ok := allowed["validator"]; ok {
		for _, e := range cfg.Validations {
			out.keys = append(out.keys, e.Key)
			out.metaByKey[e.Key] = append([]string(nil), e.MetaArgs...)
			if len(e.Commands) == 0 {
				continue
			}
			spec, ok := extractCommandSpec(e.Commands[0].Args)
			if ok {
				out.validatorByKey[e.Key] = spec
			}
		}
	}
	sort.Strings(out.keys)
	return out
}
