library generated_config;

// Generated by splash. Do not edit.

const String fieldsTextInputValueKey = 'fieldsTextInputValue';

const Map<String, String> textByKey = {
  fieldsTextInputValueKey: 'example value',
};

const Map<String, List<String>> metaArgsByKey = {
  fieldsTextInputValueKey: ['meta', '--status', 'draft', '--app', 'v1'],
};
