package generatedconfig

// Code generated by flyb. DO NOT EDIT.

const FieldsTextInputValueKey = "fieldsTextInputValue"

var TextByKey = map[string]string{
	FieldsTextInputValueKey: "example value",
}

var MetaArgsByKey = map[string][]string{
	FieldsTextInputValueKey: []string{"meta", "--status", "draft", "--app", "v1"},
}
