library generated_config;

// Generated by flyb. Do not edit.

class CommandFlag {
  final String kind;
  final String name;
  final List<String> schema;
  final List<List<String>> schemas;

  const CommandFlag({
    required this.kind,
    required this.name,
    required this.schema,
    this.schemas = const [],
  });
}

class CommandSpec {
  final List<String> commandPath;
  final bool adminOnly;
  final List<CommandFlag> flags;

  const CommandSpec({
    required this.commandPath,
    required this.adminOnly,
    required this.flags,
  });
}

const String fieldsTextInputValueValidationKey = 'fieldsTextInputValueValidation';

const Map<String, CommandSpec> validationByKey = {
  fieldsTextInputValueValidationKey: CommandSpec(
    commandPath: ['validate', 'text-input', 'value'],
    adminOnly: false,
    flags: [
      CommandFlag(
        kind: 'string',
        name: 'value',
        schema: [
          'schema',
          'string',
          '--required',
          '--min-length',
          '1',
          '--max-length',
          '120',
        ],
      ),
    ],
  ),
};
