package generatedconfig

// Code generated by flyb. DO NOT EDIT.

type CommandFlag struct {
	Kind    string
	Name    string
	Schema  []string
	Schemas [][]string
}

type CommandSpec struct {
	CommandPath []string
	AdminOnly   bool
	Flags       []CommandFlag
}

const FieldsTextInputValueValidationKey = "fieldsTextInputValueValidation"

var ValidationByKey = map[string]CommandSpec{
	FieldsTextInputValueValidationKey: {
		CommandPath: []string{"validate", "text-input", "value"},
		AdminOnly:   false,
		Flags: []CommandFlag{
			{
				Kind:   "string",
				Name:   "value",
				Schema: []string{"schema", "string", "--required", "--min-length", "1", "--max-length", "120"},
			},
		},
	},
}
